# Generated by Django 2.1.7 on 2019-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('stream', models.CharField(choices=[('cse', 'Cse'), ('ece', 'Ece')], max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
