# Generated by Django 2.1.7 on 2019-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
