# Generated by Django 2.2.2 on 2019-06-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
